language: python
dist: xenial
matrix:
  include:
    - python: "2.7"
      env: YAJL_VERSION=1.0.12
    - python: "2.7"
    - python: "3.4"
      env: YAJL_VERSION=1.0.9
    - python: "3.4"
    - python: "3.5"
      env: UPLOAD_C_COVERAGE=yes
    - python: "3.5"
      env: YAJL_VERSION=cant_find_it
    - python: "3.6"
    - python: "3.7"
    - python: "3.7"
      env: YAJL_VERSION=none
    - python: "3.8"
    - python: "3.9-dev"
    - python: "pypy"
addons:
  apt:
    packages: [libyajl-dev]
install:
  - |
    if [ -n "$YAJL_VERSION" ]; then
      sudo apt purge -y libyajl-dev libyajl2
      if [ "$YAJL_VERSION" = cant_find_it ]; then
        export YAJL_DLL=/usr/lib/libyajl_cannot_be_found.so
      elif [ "$YAJL_VERSION" != none ]; then
        wget https://github.com/lloyd/yajl/archive/${YAJL_VERSION}.zip
        unzip ${YAJL_VERSION}.zip
        cd yajl-${YAJL_VERSION}
        ./configure && make all && sudo make install
        sudo ldconfig
        cd ..
      fi
    fi
  - pip install cffi pytest-cov
  - CFLAGS='--coverage' LDFLAGS='--coverage' python setup.py develop
script:
  - python -mdoctest ijson/common.py
  - pytest -v --cov
after_success:
 - |
   if [ "$UPLOAD_C_COVERAGE" = yes ]; then
     pip install cpp-coveralls
     coveralls --gcov-options '\-lp'
   else
     pip install coveralls
     coveralls
   fi
