language: python
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
addons:
  apt:
    packages: [libyajl-dev]
install:
  - pip install cffi
  - cd ${TRAVIS_BUILD_DIR}
  - pip install .
script:
  - pip install coverage coveralls
  - coverage run tests.py
after_success:
 - coveralls
