language: python
dist: xenial
matrix:
  include:
    - python: "2.7"
      env: YAJL_VERSION=1.0.12
    - python: "2.7"
    - python: "3.4"
      env: YAJL_VERSION=1.0.9
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.7"
      env: YAJL_VERSION=none
addons:
  apt:
    packages: [libyajl-dev]
install:
  - |
    if [ -n "$YAJL_VERSION" ]; then
      sudo apt purge -y libyajl-dev libyajl2
    fi
    if [ -n "$YAJL_VERSION"  -a "$YAJL_VERSION" != none ]; then
      wget https://github.com/lloyd/yajl/archive/${YAJL_VERSION}.zip
      unzip ${YAJL_VERSION}.zip
      cd yajl-${YAJL_VERSION}
      ./configure && make all && sudo make install
      sudo ldconfig
    fi
  - pip install coveralls cffi pytest-cov
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py develop
script:
  - python -mdoctest ijson/common.py
  - pytest tests.py -v --cov
after_success:
 - coveralls
